version: "3"

services:
  metabase:
    image: metabase/metabase:v0.35.4
    restart: always
    environment:
      JAVA_TIMEZONE: Asia/Bangkok
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: '${POSTGRES_DB}'
      MB_DB_PORT: 5432
      MB_DB_USER: '${POSTGRES_USER}'
      MB_DB_PASS: '${POSTGRES_PASSWORD}'
      MB_DB_HOST: metabase-db
    ports:
      - '3000:3000'

  metabase-db:
    image: postgres:12.3-alpine
    restart: always
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'