version: "3"

services:
  metabase:
    image: metabase/metabase:v0.32.9
    volumes:
      - ./metabase-data:/metabase-data
    environment:
      JAVA_TIMEZONE: ICT
      MB_DB_FILE: /metabase-data/metabase.db
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: '${POSTGRES_DB}'
      MB_DB_PORT: 5432
      MB_DB_USER: '${POSTGRES_USER}'
      MB_DB_PASS: '${POSTGRES_PASSWORD}'
      MB_DB_HOST: metabase-db

    ports:
      - '3000:3000'

  metabase-db:
    image: postgres:10.4
    restart: always
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
  
  postgres:
    image: postgres:10.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"